### ISSUE TITLE
Travis support

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-doc#12]
I have written a module to ease continuous integration of HPP on travis-ci.org: https://github.com/jmirabel/travis-submodule
It eases writing Travis configuration files to check the project on both linux and OSX.

As an example, you can have a look at https://github.com/jmirabel/hpp-model and https://travis-ci.org/jmirabel/hpp-model

Do you think it suited for the whole project ?

**Comment by olivier-stasse** [comment]
Did you have a look to jrl-travis ?

**Comment by jmirabel** [comment]
I did have a quick look at jrl-travis. The reason I choose to write my own submodule are:
- I wanted to have the ability to install both devel and master branch,
- I did not want to pollute jrl-travis with hpp specific macros (which are easing writing travis scripts)
- at this points, coveralls is not very relevant as most of the code is not unit-tested...
