### ISSUE TITLE
gepetto-viewer-server throws core dumped errors

### ISSUE THREAD

**Issue by airobert** [humanoid-path-planner/hpp-doc#14]
Dear HPP developer, 
I got the following error after I run gepetto-viewer-server  (stable version)
terminate called after throwing an instance of 'CORBA::TRANSIENT'
Aborted (core dumped)

Is that a problem about installation or do I need to change some configurations maybe?

Thanks!

**Comment by jmirabel** [comment]
That's a common problem with CORBA. I have written a troubleshooting section: https://github.com/jmirabel/gepetto-viewer-corba#troubleshooting

I wrote from memory so it might not be error proof. Let me know if the instructions did not fix the issue.

**Comment by airobert** [comment]
Sorry Joseph,

I got this problem from my personal computer. I haven't tried it again yet.

I will do it tonight if that's ok.

Sorry about the delay.
Robert

On 7 June 2016 at 15:12, Joseph Mirabel <notifications@github.com> wrote:

> Is this fixed ? Can I close the issue ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/humanoid-path-planner/hpp-doc/issues/14#issuecomment-224275881>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACaalXh9MYq3n5PIgtCyW5_k5tBLWcXpks5qJW5bgaJpZM4IuTnB>
> .
>



-- 

Cordialement/Regards,
Robert (Shuai Wang) @ LAAS-CNRS
https://airobert.github.io/

**Comment by airobert** [comment]
Dear Joseph,

I still have the error:

localhost ~: gepetto-viewer-server
terminate called after throwing an instance of 'CORBA::TRANSIENT'
Aborted (core dumped)
localhost ~: sudo service omniorb4-nameserver restart
 * Restarting omniORB name server:  omniNames                            [
OK ]
localhost ~: gepetto-viewer-server
terminate called after throwing an instance of 'CORBA::TRANSIENT'
Aborted (core dumped)

But I have decided to buy a desktop. My current chromebook is by no means
suitable for this internship.
Please close the issue.

Thanks for the answer.

PS: there is a typo on your page:
To check* is* the server is running, run:


On 7 June 2016 at 15:12, Joseph Mirabel <notifications@github.com> wrote:

> Is this fixed ? Can I close the issue ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/humanoid-path-planner/hpp-doc/issues/14#issuecomment-224275881>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACaalXh9MYq3n5PIgtCyW5_k5tBLWcXpks5qJW5bgaJpZM4IuTnB>
> .
>



-- 

Cordialement/Regards,
Robert (Shuai Wang) @ LAAS-CNRS
https://airobert.github.io/

**Comment by davidpagnon** [comment]
Hi all, same issue here. Any solution found? Thanks

**Comment by jmirabel** [comment]
The omniname server isn't used anymore for the viewer so the issue cannot be the same. Could you provide more details ?
