### ISSUE TITLE
Problem with makefile

### ISSUE THREAD

**Issue by oguzhancebe** [humanoid-path-planner/hpp-doc#18]
Hello,
I added the following line to bash.rc
`export DEVEL_DIR="hppdev"`
And I followed the installation guide, yet when I
`make robot_state_chain_publisher.install;`
I get the following error
```
robot_state_chain_publisher already checkout out.
mkdir -p hppdev/src/robot_state_chain_publisher/build-rel; \
	cd hppdev/src/robot_state_chain_publisher/build-rel; \
	cmake -DCMAKE_INSTALL_PREFIX=hppdev/install -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release \ -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-g -O3 -DNDEBUG"  ..
CMake Error: The source directory "/home/oguz14/hppdev/src/hppdev/src/robot_state_chain_publisher" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[1]: *** [robot_state_chain_publisher.configure_nodep] Error 1
make[1]: Leaving directory `/home/oguz14/hppdev/src'
make: *** [robot_state_chain_publisher.configure] Error 2
```
I see a robot_state_chain_publisher folder is cloned to my hppdev/src, but an hppdev/src/hppdev/src/robot_state_chain_publisher/build-rel folder is also created, which seemed strange and this folder is empty and thus, the CMake error.

Can you help me about this?

**Comment by jmirabel** [comment]
Hello,
`DEVEL_DIR` must be a absolute path and a relative one.

**Comment by jmirabel** [comment]
However, the error message suggests something else. `robot_state_chain_publisher` was not downloaded so I guess you tried re-running `make robot_state_chain_publisher.install`.
After making sure DEVEL_DIR is an absolute path, could you check if file `$DEVEL_DIR/src/robot_state_chain_publisher/CMakeLists.txt` exists ?

**Comment by oguzhancebe** [comment]
> DEVEL_DIR must be an absolute path and a relative one.

Sorry for the novice mistake. Setting it as an absolute path solved the problem. 
But now, `make all` gives the following error

-- checking for module 'hpp-statistics >= 1.1'
--   found hpp-statistics , version 1.1
-- Pkg-config module hpp-statistics v1.1 has been detected with success.
-- hpp-wholebody-step >= 4 is required.
-- checking for module 'hpp-wholebody-step >= 4'
--   package 'hpp-wholebody-step >= 4' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  cmake/pkg-config.cmake:282 (PKG_CHECK_MODULES)
  cmake/pkg-config.cmake:447 (ADD_DEPENDENCY)
  CMakeLists.txt:62 (ADD_REQUIRED_DEPENDENCY)


-- Doxygen rendering: using LaTeX backend
-- Configuring incomplete, errors occurred!
See also "/home/oguz14/hppdev/src/hpp-manipulation/build-rel/CMakeFiles/CMakeOutput.log".
make[1]: *** [hpp-manipulation.configure_nodep] Error 1
make[1]: Leaving directory `/home/oguz14/hppdev/src'
make: *** [hpp-manipulation.configure] Error 2

**Comment by jmirabel** [comment]
Thanks for the report. This is an issues in the target dependencies in our `Makefile`. I will fix it.

Meanwhile, if you do not plan to work with humanoid robots, you can change line 16 of `$DEVEL_DIR/src/Makefile` from
```bash
HUMANOID=TRUE
```
to
```bash
HUMANOID=FALSE
```

**Comment by jmirabel** [comment]
2106800dff038978c3f567b6e46086902f7017b2 should fix the target dependency issue.

**Comment by jmirabel** [comment]
Closing because the problem seems to be solved.
