### ISSUE TITLE
Clean dependencies

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-doc#22]
The following dependencies are not needed anymore:
- source-highlight
- asciidoc
- autoconf
- ros-kinetic-resource-retriever

I do not know who needs:
- bison
- flex
- ros-indigo/kinetic-kdl-parser
- ros-indigo/kinetic-common-msgs
- ros-indigo/kinetic-tf: ghost of the hpp_ros package that used rviz as a viewer ?
- ros-indigo/kinetic-tf-conversions: ghost of the hpp_ros package that used rviz as a viewer ?

**Comment by jmirabel** [comment]
- ros-kinetic-common-msgs and ros-kinetic-kdl-parser are needed for robot_state_chain_publisher, which is needed for iai_maps...

**Comment by jmirabel** [comment]
Same goes for ros-kinetic-tf and ros-kinetic-tf-conversions

**Comment by jmirabel** [comment]
Do we really need robot_state_chain_publisher ?

**Comment by florent-lamiraux** [comment]
No, we should cut the dependency in iai_maps.

**Comment by jmirabel** [comment]
This has been fixed.
