### ISSUE TITLE
Dependency graph

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-doc#25]
Hi,

I'm currently trying to generate a graph of all the dependencies between gepetto's packages, and I am using the graph generated by hpp-doc to do some checks.

I found a difference: hpp-manipulation depends on hpp-pinocchio in http://homepages.laas.fr/gsaurel/graph.svg  and not in the graph generated by hpp-doc.

So either, 
- this line is useless : https://github.com/humanoid-path-planner/hpp-manipulation/blob/master/CMakeLists.txt#L56
- we don't care, because hpp-manipulation depends on hpp-constraints, which depends on hpp-pinocchio ; but in this case we should remove other arrows in our graphs / dependencies in our packages.

What do you think ?

**Comment by jmirabel** [comment]
Pushing this to its extreme, the only dependency left would be `hpp-core`...

I would prefer to keep the explicit dependence to `hpp-pinocchio`, for clarity. However, it isn't a strong preference.

**Comment by florent-lamiraux** [comment]
The directive ADD_DOC_DEPENDENCY is necessary to build html links to hpp-pinocchio classes in hpp-manipulation documentation. It does not however add hpp-pinocchio in the "Requires" filed of hpp-manipulation.pc. That is why the dependency does not appear in the graph generated by hpp-doc.

I think that this behaviour is desirable.

**Comment by nim65s** [comment]
understood, thanks ! :)
