### ISSUE TITLE
Tests disabled for hpp-pinocchio, hpp-core & hpp-constraints

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-doc#29]
Hi,

The commit 1e88828ada012d5d8df4fc39b854f7ccf4ebe69a disabled tests for hpp-pinocchio, hpp-core & hpp-constraints. What was the reason behind that ? Shouldn't we run them again ?

**Comment by jmirabel** [comment]
They are disabled because they are useful only to developers and their compilation is very time-consuming.

Developers are expected to enable them by hand. Although it is not specified anywhere, when developers do `make test`, the unit tests are first compiled.

**Comment by nim65s** [comment]
Ok, but shouldn't they be enabled for the CI ?

**Comment by jmirabel** [comment]
They are. The compilation is only delayed to target `test` instead of target `all`.

**Comment by nim65s** [comment]
I see, thanks :)
