### ISSUE TITLE
doxygen build

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-doc#36]
Hi,

I can't build the docker container for 14.04 CI, because of
https://github.com/humanoid-path-planner/hpp-doc/blob/master/.dockers/ubuntu-14.04/Dockerfile.premade#L6

I don't see any rule about doxygen 1.8.10… Was it removed recently ? Should I remove this line from this Dockerfile ?

**Comment by florent-lamiraux** [comment]
From what I remember, in Ubuntu 14.04, I used to compile doxygen from source since the official ubuntu version did crash when handling doxytag files. Target "doxygen-1.8.10.install " is provided in https://raw.githubusercontent.com/humanoid-path-planner/hpp-doc/ubuntu-14.04/doc/Makefile

**Comment by nim65s** [comment]
Thanks for the pointer.
`${WGET} -O - "ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.linux.bin.tar.gz" | ${TAR} -xz;\`
This is exactly what we were talking about this morning.
