### ISSUE TITLE
HPP installation failed on osgPlugin 

### ISSUE THREAD

**Issue by BoSmallEar** [humanoid-path-planner/hpp-doc#47]
Hi,
I'm trying to install HPP stable version on ubuntu xenial and I encounter the following problem while doing **make all** in the final step. The complier says:

/home/zzliu/HPP/src/osg-dae/src/osgPlugins/dae/daeRTransforms.cpp:47:69: error: invalid conversion from ‘osg::Callback*’ to ‘osg::NodeCallback*’ [-fpermissive]
     osg::NodeCallback* pNodeCallback = resultNode->getUpdateCallback();
                                                                     ^
/home/zzliu/HPP/src/osg-dae/src/osgPlugins/dae/daeRTransforms.cpp:47:70: error: cannot convert from pointer to base class ‘osg::Callback’ to pointer to derived class ‘osg::NodeCallback’ because the base is virtual
     osg::NodeCallback* pNodeCallback = resultNode->getUpdateCallback();

This issue is related to the osg plugin therefore I also tried to download the OpenSceneGraph and repalce the source code of the plugin with the latest version. However, although the plugin compiles successfully, there are some linking issues between packages so I still can't install HPP. Does anyone know how to fix this problem?

**Comment by jmirabel** [comment]
Can you provide the output of:
- `dpkg -l "*openscenegraph*"`
- `pkg-config --modversion openscenegraph`

Actually, you can install this package from binaries:
- `sudo apt-get install robotpkg-osg-dae`
- you must then modify your config.sh to include /opt/openrobots/lib64 to LD_LIBRARY_PATH.
- in the Makefile, remove osg-dae.install where it appears

**Comment by BoSmallEar** [comment]
Here is the output
![Screenshot from 2019-05-15 15-58-53](https://user-images.githubusercontent.com/10669600/57805209-7b270f80-772a-11e9-9247-30af6ebb3b16.png)

**Comment by jmirabel** [comment]
Those output are correct. It should work just fine.

**Comment by jmirabel** [comment]
If you prefer to skip installation from source, you can install hpp using
`sudo apt-get install robotpkg-hpp-tutorial`

@nim65s Could you update the file doc/instructions.md on master branch to include an *installation from binaries* section ? If the only package to install if hpp-tutorial, then I can do it.

**Comment by BoSmallEar** [comment]
Hi jmirabel,
Thanks for the help! 
However, after I install the package from binaries, there seems still be linking problems(similar to the problem when I substitute the source code with the lastest plugin):
![Screenshot from 2019-05-15 16-42-42](https://user-images.githubusercontent.com/10669600/57808012-7d8c6800-7730-11e9-857e-be85d0e669ba.png)
Then I install hpp by directly install the robotpkg, but it is still not working as I go through the tutorial:
![image](https://user-images.githubusercontent.com/10669600/57808226-e8d63a00-7730-11e9-84e6-b324a80f2513.png)
Sorry I'm not familiar with linking libraries and I have no idea what should I do to make it working,

**Comment by jmirabel** [comment]
Launch `gepetto-gui` instead.

**Comment by jmirabel** [comment]
I fixed the webpage (2be7f9a)

**Comment by BoSmallEar** [comment]
@jmirabel  I saw your modification and add the environment variables #48 , however, the documentation is missing in  **/opt/openrobots/share/doc.**  In addition, the gepetto-gui also failed.
![image](https://user-images.githubusercontent.com/10669600/57874819-6d7f9180-77df-11e9-9023-e2d1e43c6601.png)

**Comment by jmirabel** [comment]
> the documentation is missing in /opt/openrobots/share/doc

I noticed that. @nim65s I couldn't find how to specify the default options for robotpkg build bot.

> In addition, the gepetto-gui also failed.

Output of:
- `which gepetto-gui`
- `dpkg -l "*gepetto-viewer*"`

**Comment by BoSmallEar** [comment]
![image](https://user-images.githubusercontent.com/10669600/57886824-15a35380-77fc-11e9-9011-ba61e6c53558.png)

**Comment by jmirabel** [comment]
What's weird is that it shouldn't use NamingContext at all...

Output of:
- `gepetto-gui --verbose`
- `cat /opt/openrobots/etc/gepetto-gui/settings.conf` if it exists.

You can try adding the line below to `/opt/openrobots/etc/gepetto-gui/settings.conf` (creating it if it does not exists)
```
[omniORB]
endPoint=:::12321
```

**Comment by BoSmallEar** [comment]
Still not working
![image](https://user-images.githubusercontent.com/10669600/57945835-e4cd2800-78a8-11e9-96de-d14aa8ad3b9a.png)

**Comment by nim65s** [comment]
>     * you must then modify your config.sh to include /opt/openrobots/lib64 to LD_LIBRARY_PATH.

robotpkg tries not to use `lib64`, so you should include `/opt/openrobots/lib` instead.

**Comment by jmirabel** [comment]
robotpkg-osg-dae still installs stuff in lib64.

**Comment by nim65s** [comment]
It should not. Are you on `3.2.1r2` ?

**Comment by nim65s** [comment]
I have:
```
╰─>$ dpkg -L robotpkg-osg-dae | grep lib
/opt/openrobots/lib
/opt/openrobots/lib/pkgconfig
/opt/openrobots/lib/pkgconfig/osg-dae.pc
/opt/openrobots/lib/osgPlugins-3.2.1
/opt/openrobots/lib/osgPlugins-3.2.1/osgdb_dae.so
```

**Comment by jmirabel** [comment]
> It should not. Are you on `3.2.1r2` ?

Ah, it's in both. I didn't see it:
```
╰─> $ apt-file list robotpkg-osg-dae 
...
robotpkg-osg-dae: /opt/openrobots/lib/osgPlugins-3.2.1/osgdb_dae.so
robotpkg-osg-dae: /opt/openrobots/lib/pkgconfig/osg-dae.pc
robotpkg-osg-dae: /opt/openrobots/lib64/osgPlugins-3.2.1/osgdb_dae.so
...
```

**Comment by nim65s** [comment]
I think that `apt-file`shows outdated informations.

**Comment by jmirabel** [comment]
On which distribution are you ?

**Comment by BoSmallEar** [comment]
I've successfully installed HPP from the C++ source code. Thanks for all the help! I've opened another issue for another problem.
