### ISSUE TITLE
Add path planner 

### ISSUE THREAD

**Issue by BoSmallEar** [humanoid-path-planner/hpp-doc#50]
Hi,
I want to use my own path planner (based on A*)  with the HPP framework. I'm a little confused about how to do so. Do I have to inherit from the hpp::core::PathPlanner class and override the methods? Do I need to make any modifications on the corba server side? I noticed that there is a void hpp::corbaserver::Problem::selectPathPlanner method for the client.

**Comment by BoSmallEar** [comment]
Sorry, I just saw there is a tutotial-2 for this issue. I will re-open if needed.

**Comment by BoSmallEar** [comment]
Actually I want to modify the path-planning part of the rbprm module and keep other parts in the pipeline unchanged, however this module is very complicated and it run several servers. Therefore how should I modify this module to add another path planner?

**Comment by jmirabel** [comment]
There are several steps to follow.
- Implement your algorithm that inherits from PathPlanner.
- Make it available to the ProblemSolver. For this, either:
  - follow tutorial 2 and make a new executable,
  - (the less intrusive method) use plugins. You can find an example plugin in hpp-core/tests/. If you use plugins, you must add something like `ps.loadPlugin("plugin.so")` to your script.
- Make sure RBPRM uses your planner at the right time.

For the last step, you have to be more precise. What step of the RBPRM planner do you want to modify ? the algo for planning a trajectory of the root, the algo for planning a trajectory of the root or any other ?

**Comment by BoSmallEar** [comment]
I want to change the algo for planning a trajectory of the root(the path used for contact generation), I think the server side of this module seems to be very different from the original corbaserver.

**Comment by jmirabel** [comment]
Then it should be sufficient to create a planner class and use
selectPathPlanner.
For testing purpose, you can do it in the source file containing the main
function, in hpp-rbprm-corba.

**Comment by BoSmallEar** [comment]
You mean I can write my planner in hpp-rbprm-corba.cc like the tutorial and select the planner before starting corba server?

**Comment by jmirabel** [comment]
Method oneStep fills the roadmap with configurations and paths. It is responsible **neither** for checking whether the problem is solved nor for computing the solution path.

> I have to implement the planner with a explicit roadmap?

I don't understand what you mean.

**Comment by jmirabel** [comment]
I hope you solved your problem. I close this because it has been inactive for some time. @BoSmallEar re-open if necessary.
