### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by olivier-stasse** [humanoid-path-planner/hpp-doc#6]
Dear HPP,
I am not able to install the hpp system. At stage 7 I got this weird bug:
	cd /home/ostasse/devel/ros-indigo-1//src/doxygen-Release_1_8_10/build; \
	cmake -DCMAKE_INSTALL_PREFIX=/home/ostasse/devel/ros-indigo-1//install -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-g -O3 -DNDEBUG" -DCMAKE_BUILD_TYPE=Release ..
CMake Error: Error in cmake code at
/home/ostasse/devel/ros-indigo-1/src/doxygen-Release_1_8_10/version:1:
Parse error.  Expected a command name, got unquoted argument with text "1.8.10".
CMake Error at CMakeLists.txt:29 (include):
  include could not find load file:

    version

Do you have a hint ?

**Comment by florent-lamiraux** [comment]
Hello Olivier,

Which ubuntu version are you using ?

Florent

**Comment by jmirabel** [comment]
Could the problem be that the line `include(version)` in the doxygen `CMakeLists.txt` should load the file `cmake/version.cmake` but finds file `VERSION` instead ?

Could you try again after having replaced line `include(version)` by `include(cmake/version.cmake)` ?

**Comment by olivier-stasse** [comment]
Dear Florent and Jospeh,
Thanks for your quick answer.
It was my fault. During the installation it seems that doxygen did not uncompress properly and was missing some files. I removed the directory and rerun stage 7.
The bug disappeared.
Thanks again.
