### ISSUE TITLE
Can I download and use HPP software?

### ISSUE THREAD

**Issue by Cucumberkjs** [humanoid-path-planner/hpp-doc#62]
Hi, I'm a graduate student majoring robotics.
I appreciate great inspiring works in this project.
I thought I could use or refer to the software in my research works, but I could not download it from the download page in the HPP homepage.
Can I download and use this software?

**Comment by jmirabel** [comment]
Go to https://humanoid-path-planner.github.io/hpp-doc/download.html and select *Stable* in the drop-down menu.

Then follow the binary installation instructions.

**Comment by Cucumberkjs** [comment]
Thanks, I could not access the page from desktop but I found I can access the page on mobile.

**Comment by jmirabel** [comment]
Can you post a screenshot of the page you get on your desktop ?

**Comment by Cucumberkjs** [comment]
![capture](https://user-images.githubusercontent.com/7326856/89629346-a1f5d680-d8d8-11ea-8e5a-bc552a7d784a.PNG)

"Please select the version you want to install" does not disappear
both from windows 10 chrome and ubuntu 18.04 firefox

**Comment by jmirabel** [comment]
You can see what are the errors (in Firefox) by hitting F12 and going to the console tab.

**Comment by Cucumberkjs** [comment]
![image](https://user-images.githubusercontent.com/7326856/89629825-6b6c8b80-d8d9-11ea-9c41-a245fe8490d3.png)
This is the error

**Comment by jmirabel** [comment]
No idea why `showdown` is not parsed correctly...

**Comment by jmirabel** [comment]
Is Firefox up-to-date ?

**Comment by jmirabel** [comment]
Anyway, you can find the instructions for *stable* install here: https://github.com/humanoid-path-planner/hpp-doc/blob/master/doc/instructions.md

**Comment by Cucumberkjs** [comment]
Thanks, I could do the installation with the mobile page after your first reply and  it was not big problem with me.
Just wanted to report the problem.
Firefox is the latest version, I have no idea but I guess language or location could be the only difference? (South Korea)
Anyway, many thanks for your help :)
