### ISSUE TITLE
branch master does not compile

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-doc#71]
I am trying to compile hpp-doc branch master in Ubuntu-18.04 and I get several errors:
`PROJECT_DESCRIPTION` is not defined when calling `cmake/base.cmake`.

When I fix the issue, installation fails since "/workspace/src/hpp-doc/build-rel/doc/doxygen-xml/index.xml" is not generated although `GENERATE_XML` is set to yes in `doc/Doxyfile.extra.in`.

**Comment by nim65s** [comment]
I opened https://gitlab.laas.fr/humanoid-path-planner/hpp-doc/-/merge_requests/8 to fix this.
16.04 is still not building because of  https://github.com/humanoid-path-planner/hpp-corbaserver/issues/137

**Comment by nim65s** [comment]
Actually, this issue was caused by an update of the submodule, which was not yet in the master branch at the time of opening and closing this issue. It was fixed in #72
