### ISSUE TITLE
[ubuntu 14] cmake is not able to find boost libraries installed in /usr/lib/x86_64-linux-gnu

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-doc#8]
Since ubuntu 14, boost libraries are installed in /usr/lib/x86_64-linux-gnu 
in 64 bits.

By default cmake is not able to look there.

A temporary fix is to export BOOST_LIBRARYDIR environment variable containing 
this address

**Comment by jmirabel** [comment]
According to this [bug report](https://public.kitware.com/Bug/bug_relationship_graph.php?bug_id=12037&graph=relation), the bug has been fixed in version 2.8.5 of cmake. You may find information in the discussion about the bug.

**Comment by stonneau** [comment]
Well, in this case maybe we should change the minimum cmake requirement 
CMAKE_MINIMUM_REQUIRED(VERSION 2.6) no ?
I can do it

**Comment by jmirabel** [comment]
It would be a good thing, indeed.
