### ISSUE TITLE
Install from source no openscenegraph-osgQt

### ISSUE THREAD

**Issue by Thompson104** [humanoid-path-planner/hpp-doc#83]
Hello,

Thank you for making this repo public. Really great work. I run into a problem while trying to do a source install on ubunu 18.04. I followed the link as in [here](https://humanoid-path-planner.github.io/hpp-doc/download.html). 

I got the following error while trying to execute `make all` (no problems found in previous steps):

![image](https://user-images.githubusercontent.com/28070085/130370261-bc40c5b6-1ab1-4b3f-8f99-39bcbdeebfd1.png)

Do you mind letting me know how to solve this issue? I have took a look at osg and it is not very clear how to install the osgQT.

Thank you in advance.

**Comment by Thompson104** [comment]
I have re-installed ubutun 18.04 and this problem still happens. For anyone who run into this problem, `sudo apt-get install robotpkg-qt4-osgqt` would do the trick.

I'm wondering if the developers could add this in the installation guide? Thanks.  

I'm going to close this issue as soon as the development team noticed this. Sorry for the trouble.

**Comment by Thompson104** [comment]
Also, I have the following error during make all:
`[ 25%] Building CXX object src/CMakeFiles/hpp-tutorial-2-server.dir/tutorial_2.cc.o
In file included from /workspace/src/hpp_tutorial/src/tutorial_2.cc:32:
/workspace/install/include/hpp/corbaserver/server.hh:14:11: fatal error: omniORB4/CORBA.h: No such file or directory
   14 | # include <omniORB4/CORBA.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
`
A screenshot has been attached:

![image](https://user-images.githubusercontent.com/28070085/130385022-e4871941-56f3-4de2-aec7-39f444f88a84.png)

It looks like the pull request from [here](https://github.com/humanoid-path-planner/hpp-doc/pull/73) was not successfully merged. I manually changed the cmake files as detailed in [here](https://github.com/humanoid-path-planner/hpp-corbaserver/commit/c30ef40e558d46accc0cf1e501c4670616ea3092) to fix it.

**Comment by nim65s** [comment]
Hi @Thompson104,

Thanks for your feedback.

For your first issue, you got it right, and I'll add this to the docs, but I suggest you go for Qt5 instead of Qt4, so: `sudo apt install robotpkg-qt5-osgqt`. 

For your second issue, your second link clearly shows that this was merged in https://github.com/humanoid-path-planner/hpp-corbaserver/pull/140 and is available since v4.11.0. But it looks like we forgot to update stable to v4.11.0. I'll fix this too, thanks for the notice !

**Comment by Thompson104** [comment]
Thank you @nim65s for your quick reply. I have tried the `sudo apt install robotpkg-qt5-osgqt.` However, the same error shows up: 
![image](https://user-images.githubusercontent.com/28070085/130553966-1d744835-e474-4df1-94fc-03110bfc588b.png)

With the qt-osgqt: I have changed `QT_VERSION=5` in the "Makefile" under /hpp/src. Then I can compile the system after `sudo apt install qttools5-dev-tools qttools5-dev`. However, I have the following two problems:

[1] After make all (successful), when I take a look at the doc file as in `$DEVEL_HPP_DIR/install/share/doc/hpp-doc/index.html`. It looks like those packages don't have a doc file:
![image](https://user-images.githubusercontent.com/28070085/130554344-058bb3f9-946a-4608-b4c3-cfee5edbf57d.png)


[2] After sourcing the config.sh file, when I try to follow the tutorial 1 [here](https://humanoid-path-planner.github.io/hpp-doc/tutorials.html). The commnad `gepetto-gui ` gives me segmentation fault 
![image](https://user-images.githubusercontent.com/28070085/130554410-c0ee1e9b-1747-4c68-9097-0a8b398675ad.png). In addition, the "tutorial1-details" in the tutorial page  [here](https://humanoid-path-planner.github.io/hpp-doc/tutorials.html) seems to be dead. 


I wonder if you may suggest how to fix those two problems?  

Apologize if I ask too many questions here. I just really want to try this nice repo and play with it. Thank you for your help.

**Comment by nim65s** [comment]
For your first question, I don't understand which package doesn't have which file.

For the second, I'll try to reproduce the issue

**Comment by Thompson104** [comment]
> For your first question, I don't understand which package doesn't have which file.
> 
> For the second, I'll try to reproduce the issue

**Comment by Thompson104** [comment]
For the first question, please allow me to clarify. 

> For your first issue, you got it right, and I'll add this to the docs, but I suggest you go for Qt5 instead of Qt4, so: sudo apt install robotpkg-qt5-osgqt

I tried this command with qt5 and use make all to compile. However, I got the following error 
![image](https://user-images.githubusercontent.com/28070085/130636353-d6ef27dd-0dea-483a-bb81-d346a3277100.png)

Based on this error, I have changed the qt version in the "Makefile" under /hpp/src from 4 to 5. After `sudo apt install qttools5-dev-tools qttools5-dev`, I can successfully compile the project. Howver then I runinto the segmentation fault while try to run the tutorial scripts.

**Comment by florent-lamiraux** [comment]
> 
> [1] After make all (successful), when I take a look at the doc file as in `$DEVEL_HPP_DIR/install/share/doc/hpp-doc/index.html`. It looks like those packages don't have a doc file:

Which version of hpp-doc do you install ? This should have been fixed in branch `origin/stable`.

**Comment by Thompson104** [comment]
@florent-lamiraux  I'm not very sure about this. I followed [this](https://humanoid-path-planner.github.io/hpp-doc/download.html) link under "stable-source" with Ubuntu 18.04.

**Comment by florent-lamiraux** [comment]
Can you contact me by email at florent.lamiraux at laas dot fr to organize a video conference ?

**Comment by florent-lamiraux** [comment]
Did you fix your issue ? I did not received any email.

**Comment by Thompson104** [comment]
Thank you for your reply and really appreciate for your help. I have managed to install the packages from source instead of usuing the link [here](https://humanoid-path-planner.github.io/hpp-doc/download.html).

Again, thank you. I'm closing it.
