### ISSUE TITLE
HPP conda installation issue

### ISSUE THREAD

**Issue by Dyymon** [humanoid-path-planner/hpp-doc#93]
Hello,

 I was recently trying to install HPP through conda via instructions on the [website](https://humanoid-path-planner.github.io/hpp-doc/download.html) however I was met with an issue.
  I have undergone the installation without failure but whenever I run any HPP code through python I am met with ImportError.
  
  `ImportError: /home/dyymon/anaconda3/envs/hpp/lib/python3.8/site-packages/pinocchio/pinocchio_pywrap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7eigenpy9NumpyType7getTypeEv`
  
  To recreate this error one can just install HPP via the installation steps on the webpage and than just run script with
  
  `import pinocchio`
  
  My current version of pinocchio is 2.6.14, I have tried changing the version but I have been met with multiple compatibility problems while solving the environment.

**Comment by Dyymon** [comment]
@nim65s I am tagging you as we agreed

**Comment by nim65s** [comment]
Thanks @Dyymon for the report and the tag. 

I can reproduce your issue:
```Dockerfile
FROM continuumio/miniconda3

RUN conda create -n hpp -c conda-forge python=3.8 hpp-gepetto-viewer -y
SHELL ["conda", "run", "-n", "hpp", "/bin/bash", "-c"]
CMD python -c "import pinocchio; print(pinocchio.__version__, pinocchio.__file__)"
```
returns:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/hpp/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ImportError: /opt/conda/envs/hpp/lib/python3.8/site-packages/pinocchio/pinocchio_pywrap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7eigenpy9NumpyType7getTypeEv
```

So this is not an error on our side, but on our packaging.

@ymontmarin: Do you have any clue about this issue ?

Otherwise, I'll try to debug it, but I don't have a lot of time at the moment.

**Comment by nim65s** [comment]
```
(hpp) root@4ba4a366be64:/# conda list | grep pinocchio                                                                                                                                                                                                                 
hpp-pinocchio             4.15.1               ha6fd265_0    conda-forge                                                                                                                                                                                                          
pinocchio                 2.6.14           py38hac5dcfb_1    conda-forge
```

So I guess the issue is that the pinocchio version is too old, as it looks like we hit https://github.com/stack-of-tasks/pinocchio/issues/1935.

It looks like for packages depending on pinocchio, the fix should be something like https://github.com/conda-forge/crocoddyl-feedstock/pull/26

**Comment by ymontmarin** [comment]
Hi, thank you @Dyymon for the report and @nim65s for the ping !

I think you found it, i need to propagate the change on the hpp stacks.

Will do it as quickly as possible, but I am quite on a rush until next wednesday.

**Comment by ymontmarin** [comment]
Hi  @Dyymon and @nim65s
I finish a deadline rush and will bee finishing the re-release this weak. I will ping you when it is done

**Comment by ymontmarin** [comment]
Hi @Dyymon and @nim65s , the release of the hpp stack with the latest Pinocchio version is complete and the conda install command on the [website](https://humanoid-path-planner.github.io/hpp-doc/download.html) now works !

Let me know if it works for you

**Comment by Dyymon** [comment]
Hi @ymontmarin, I have tested it and it works! Thank you very much!
